# 02 · Data Understanding

## Objetivo

El objetivo de este notebook es comprender la estructura y la calidad de los datos procesados antes de comenzar el análisis de negocio.

Durante esta fase se verificará la integridad de los datos, se identificarán posibles problemas de calidad y se obtendrá una primera comprensión de la información disponible.

Al finalizar este notebook, los datos deberán estar completamente validados y listos para iniciar el análisis exploratorio y responder a las preguntas de negocio planteadas en el proyecto.

## Importación de librerías

En esta sección se importan las librerías necesarias para realizar el análisis de los datos.

Cada notebook es completamente independiente, por lo que incluye todas las librerías necesarias para poder ejecutarse desde la primera hasta la última celda.

In [7]:
import pandas as pd

## Carga de los datos procesados

En esta sección se cargan los conjuntos de datos generados durante la fase de preparación de los datos.

Estos archivos constituyen la base del análisis y serán utilizados en las siguientes fases del proyecto para evaluar la calidad de los datos y obtener una primera comprensión de su contenido.

In [8]:
# Cargar los datos procesados

customers = pd.read_csv("../data/sql/customers_sql.csv")
products = pd.read_csv("../data/sql/products_sql.csv")
orders = pd.read_csv("../data/sql/orders_sql.csv")

## Verificación de la carga

Antes de comenzar el análisis, es importante comprobar que los tres conjuntos de datos se han cargado correctamente y están disponibles para su utilización.

In [9]:
print(f"Customers: {customers.shape}")
print(f"Products : {products.shape}")
print(f"Orders   : {orders.shape}")

Customers: (12136, 4)
Products : (10, 3)
Orders   : (12135, 13)

### Observaciones

Los tres conjuntos de datos se han cargado correctamente.

El proyecto dispone de:

- **12.136** registros de clientes.
- **10** productos.
- **12.135** pedidos.

La diferencia de un registro entre las tablas **customers** y **orders** es esperable, ya que no todos los clientes tienen necesariamente un pedido asociado.

Con la carga de los datos verificada, el proyecto está preparado para comenzar el análisis de la estructura y la calidad de la información.

## Vista general de los datasets

Una vez verificada la carga de los datos, el siguiente paso consiste en comprender la estructura de cada conjunto de datos.

En esta sección se revisarán las columnas disponibles y los tipos de datos de cada tabla para obtener una visión general de la información que se utilizará durante el análisis.

In [10]:
# Información del dataset de clientes

customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 12136 entries, 0 to 12135
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customer_id     12136 non-null  int64
 1   age             12136 non-null  int64
 2   gender          12135 non-null  str
 3   loyalty_member  12136 non-null  int64
dtypes: int64(3), str(1)
memory usage: 379.4 KB

In [11]:
# Información del dataset de productos

products.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    10 non-null     int64
 1   sku           10 non-null     str
 2   product_type  10 non-null     str
dtypes: int64(1), str(2)
memory usage: 372.0 bytes

In [12]:
# Información del dataset de pedidos

orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 12135 entries, 0 to 12134
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          12135 non-null  int64
 1   customer_id       12135 non-null  int64
 2   product_id        12135 non-null  int64
 3   rating            12135 non-null  int64
 4   order_status      12135 non-null  str
 5   payment_method    12135 non-null  str
 6   total_price       12135 non-null  float64
 7   unit_price        12135 non-null  float64
 8   quantity          12135 non-null  int64
 9   purchase_date     12135 non-null  str
 10  shipping_type     12135 non-null  str
 11  addons_purchased  9196 non-null   str
 12  addon_total       12135 non-null  float64
dtypes: float64(3), int64(5), str(5)
memory usage: 1.2 MB

### Observaciones

Los tres conjuntos de datos se han cargado correctamente y presentan una estructura consistente para el análisis.

Las principales observaciones son:

- La tabla **customers** contiene información demográfica de **12.136** clientes.
- La tabla **products** incluye el catálogo de **10** productos disponibles.
- La tabla **orders** almacena **12.135** pedidos y actúa como tabla de hechos del modelo relacional.

En cuanto a la estructura de los datos:

- Los identificadores y variables numéricas presentan el tipo de dato adecuado.
- Las variables categóricas se almacenan como texto.
- La columna **purchase_date** se encuentra almacenada como texto y podrá convertirse al tipo `datetime` cuando sea necesario realizar análisis temporales.
- Se observa la existencia de valores nulos en **gender** y **addons_purchased**, que serán analizados en la siguiente sección.

## Evaluación de la calidad de los datos

Antes de comenzar el análisis de negocio, es fundamental evaluar la calidad de los datos.

En esta sección se comprobará la existencia de valores nulos y registros duplicados para determinar si es necesario realizar alguna acción adicional antes de continuar con el proyecto.

### Valores nulos

Los valores nulos pueden afectar a la calidad del análisis y a la interpretación de los resultados.

A continuación, se revisará el número de valores ausentes en cada uno de los conjuntos de datos.

In [13]:
# Valores nulos por dataset

print("Customers")
display(customers.isnull().sum())

print("\nProducts")
display(products.isnull().sum())

print("\nOrders")
display(orders.isnull().sum())

Customers

customer_id       0
age               0
gender            1
loyalty_member    0
dtype: int64

Products

product_id      0
sku             0
product_type    0
dtype: int64

Orders

order_id               0
customer_id            0
product_id             0
rating                 0
order_status           0
payment_method         0
total_price            0
unit_price             0
quantity               0
purchase_date          0
shipping_type          0
addons_purchased    2939
addon_total            0
dtype: int64

### Observaciones

La evaluación de los valores nulos muestra que, en general, los conjuntos de datos presentan una buena calidad.

Las principales observaciones son:

- La tabla **customers** contiene un único valor nulo en la columna **gender**.
- La tabla **products** no presenta valores nulos.
- La tabla **orders** contiene **2.939** valores nulos en la columna **addons_purchased**.

Dado que **addons_purchased** hace referencia a productos adicionales opcionales, es razonable considerar que estos valores nulos representan pedidos sin compras adicionales. No obstante, esta interpretación deberá validarse durante el análisis exploratorio.

En conjunto, los valores nulos identificados no representan un problema significativo para el desarrollo del proyecto.

### Registros duplicados

Los registros duplicados pueden generar resultados incorrectos y afectar a la fiabilidad del análisis.

En esta sección se comprobará si existen filas duplicadas en cada uno de los conjuntos de datos.

In [14]:
# Registros duplicados por dataset

print(f"Customers: {customers.duplicated().sum()}")
print(f"Products : {products.duplicated().sum()}")
print(f"Orders   : {orders.duplicated().sum()}")

Customers: 0
Products : 0
Orders   : 0

### Observaciones

No se han identificado registros duplicados en ninguno de los conjuntos de datos.

Este resultado indica que los datos presentan un buen nivel de integridad y que no es necesario realizar procesos de eliminación de duplicados antes de continuar con el análisis.

Junto con la evaluación de los valores nulos, puede concluirse que los datos presentan una calidad adecuada para desarrollar el análisis de negocio.

## Estadísticas descriptivas

Las estadísticas descriptivas permiten obtener una primera visión de las variables numéricas presentes en los conjuntos de datos.

A través de medidas como la media, la mediana, los valores mínimo y máximo o la desviación estándar, es posible comprender mejor las características generales de los datos antes de iniciar el análisis exploratorio.

### Dataset: Customers

En esta sección se analizan las principales variables numéricas del conjunto de datos de clientes.

In [15]:
customers.describe().T

,count,mean,std,min,25%,50%,75%,max
customer_id,12136.0,10444.218194,5619.332689,1000.0,5464.75,9916.5,15416.25,19998.0
age,12136.0,49.123187,18.121530,18.0,33.00,49.0,65.00,80.0
loyalty_member,12136.0,0.210531,0.407702,0.0,0.00,0.0,0.00,1.0

### Observaciones

Las estadísticas descriptivas del conjunto de datos **customers** permiten obtener una primera visión de las características de los clientes.

Las principales observaciones son:

- El conjunto de datos contiene información de **12.136 clientes**.
- La edad de los clientes oscila entre **18 y 80 años**, con una edad media de **49,1 años**.
- La mediana de edad es de **49 años**, lo que indica una distribución equilibrada de esta variable.
- La variable **loyalty_member** se encuentra codificada de forma binaria (0 = No, 1 = Sí) y será analizada como una variable categórica en las siguientes fases del proyecto.

En conjunto, el dataset presenta una distribución de edades amplia y adecuada para realizar análisis segmentados por grupos de edad.

### Dataset: Orders

En esta sección se analizan las principales variables numéricas del conjunto de datos **orders**.

Estas estadísticas proporcionan una primera comprensión del comportamiento general de los pedidos antes de realizar el análisis exploratorio del negocio.

In [16]:
orders.describe().T

,count,mean,std,min,25%,50%,75%,max
order_id,12135.0,6068.000000,3503.217093,1.00,3034.50,6068.00,9101.50,12135.00
customer_id,12135.0,10444.688010,5619.325872,1000.00,5466.00,9917.00,15416.50,19998.00
product_id,12135.0,5.543964,2.865945,1.00,3.00,6.00,8.00,10.00
rating,12135.0,3.103173,1.224066,1.00,2.00,3.00,4.00,5.00
total_price,12135.0,3172.521617,2543.608254,20.75,1083.54,2534.49,4718.46,11396.80
unit_price,12135.0,578.458013,313.199140,20.75,361.18,463.96,791.19,1139.68
quantity,12135.0,5.470375,2.868256,1.00,3.00,5.00,8.00,10.00
addon_total,12135.0,62.339503,58.018744,0.00,7.95,51.93,94.27,292.77

### Observaciones

Las estadísticas descriptivas del conjunto de datos **orders** permiten comprender las principales características de los pedidos registrados.

Las principales observaciones son:

- El conjunto de datos contiene **12.135 pedidos**.
- La valoración media de los pedidos es de **3,10 sobre 5**, lo que refleja un nivel de satisfacción generalmente neutro.
- El importe medio de los pedidos es de **3.172,52 €**, aunque existe una elevada variabilidad, con pedidos desde **20,75 €** hasta **11.396,80 €**.
- Los clientes adquieren una media de **5,47 unidades** por pedido.
- Los productos adicionales generan un importe medio de **62,34 €** por pedido, aunque existen pedidos sin compras adicionales y otros que alcanzan **292,77 €**.

En conjunto, las estadísticas descriptivas muestran una considerable variabilidad en el comportamiento de compra, lo que sugiere la existencia de diferentes patrones de consumo que serán analizados en la siguiente fase del proyecto.

# Conclusiones

El proceso de **Data Understanding** ha permitido validar la estructura y la calidad de los datos que se utilizarán durante el resto del proyecto.

Las principales conclusiones obtenidas son:

- Los tres conjuntos de datos presentan una estructura consistente y adecuada para el análisis.
- Los tipos de datos son apropiados para la mayoría de las variables.
- La calidad de los datos es elevada, ya que únicamente se han identificado valores nulos en campos no críticos y no existen registros duplicados.
- Las estadísticas descriptivas muestran una elevada variabilidad en las características de los pedidos, lo que sugiere la existencia de diferentes patrones de compra que podrán analizarse en las siguientes fases del proyecto.

Con la validación de la estructura y la calidad de los datos finalizada, el proyecto está preparado para comenzar el análisis exploratorio y responder a las principales preguntas de negocio definidas en el plan del proyecto.